language: java
jdk: 
 -openjdk7
 -oraclejdk7
branches:
 only:
  - "master"
notifications:
 email:
  recepients:
   - ghardard@gmail.com

  on_success: [always|never|change] # default: change
  on_failure: [always|never|change] # default: always  
