language: java
jdk:
 - oraclejdk7 
 - openjdk7
branches:
 only:
  - "master"
notifications:
 email:
  recepients:
   - ghardard@gmail.com
   - johannesh10@ru.is


  on_success: [always|never|change] # default: always
  on_failure: [always|never|change] # default: always  
