language: java

jdk:
 - openjdk7
#- oraclejdk7

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

branches:
  only:
  - master

script: 
  - mvn clean 
  - mvn compile
  - mvn package 
  - mvn test

after_script: 
  - export STAGING_SERVER=http://spacestallions-staging.herokuapp.com/
  - mvn test-compile failsafe:integration-test failsafe:verify
 
after_success:
 - mvn test jacoco:report coveralls:jacoco 
 
notifications:
  email:
    recepients:
    - ghardard@gmail.com
    - emil@8bit.is
    - johannesh10@ru.is
    - fannarl11@ru.is
    - bjossialf@gmail.com
    - arnarjonasson@gmail.com
    on_success: change
    on_failure: always

deploy:
  provider: heroku
    api_key:	 
        secure: RCFqAPCIh2nUVNI2v/es2QKLuXtQzJlVMWceV/oefecGfPRRIOB8nxk5FLgUwSdzXrm6gkOXkBhWhWtQpdmo1Eb9nBGp1Eaq9z0pm2j9E80UIejh04d+Jw/D6fuWCfx0g7Psj0kcU/usQrC4W+c2EzAT5XwKEzrY5n5vKbaxeAM=		
    app: 
	  master: spacestallions-staging
	  production: spacestallions