language: java
jdk:
 - oraclejdk7 
 - openjdk7
branches:
 only:
  - "master"
notifications:
 email:
  recepients:
   - ghardard@gmail.com
   - emil@8bit.is
   - johannesh10@ru.is
   - evillevy@gmail.com
   - bjossialf@gmail.com
   - arnarjonasson@gmail.com
   - binnih@gmail.com
   - joezombie@gmail.com
   - gislig@gmail.com
  on_success: change
  on_failure: always  
