#language is java
language: java

#tell travis which version of jdk to use
jdk: 
 - openjdk7
 - oraclejdk7
 
#tell travis to build master branch
branches:
 only:
  - "master"

script: mvn clean package compile test 

#configure notifications
notifications:
 email:
  recepients:
   - ghardard@gmail.com
   - emil@8bit.is
   - johannesh10@ru.is
   - fannarl11@ru.is
   - bjossialf@gmail.com
   - arnarjonasson@gmail.com
   - binnih@gmail.com
   - gislig@gmail.com
  on_success: change
  on_failure: always  
